"""IT-001 — Platform coverage: every vendor × category × query in PLATFORM_MAP.

Generates testing/integration/platform_coverage_results.md as a side effect.
"""
import re
from pathlib import Path

import pytest

from platforms.platform_map import PLATFORM_MAP
from validation.normalizers import (
    _INTERFACE_PARSERS,
    _OSPF_NEIGHBOR_PARSERS,
    _OSPF_DETAIL_PARSERS,
    _BGP_SUMMARY_PARSERS,
    _EIGRP_NEIGHBOR_PARSERS,
)


_VENDORS = ["ios", "eos", "junos", "aos", "routeros", "vyos"]
_REQUIRED_CATEGORIES = ["ospf", "bgp", "routing_table", "routing_policies", "interfaces"]

_RESULTS_FILE = Path(__file__).parent / "platform_coverage_results.md"


# ── Helpers ───────────────────────────────────────────────────────────────────

def _collect_coverage() -> list[dict]:
    """Return a list of coverage entries for every vendor/category/query."""
    entries = []
    for vendor in _VENDORS:
        vendor_entry = PLATFORM_MAP.get(vendor, {})
        for cat in sorted(vendor_entry.keys()):
            for query, action in sorted(vendor_entry[cat].items()):
                status = "PASS"
                issues = []

                if isinstance(action, str):
                    if not action.strip():
                        status = "FAIL"
                        issues.append("empty command string")
                    if "{vrf}" in action:
                        issues.append("plain-string VRF template (not dual-entry)")

                elif isinstance(action, dict):
                    if "default" not in action or "vrf" not in action:
                        status = "FAIL"
                        issues.append(f"missing keys: {set(action.keys())}")
                    vrf_cmd = action.get("vrf", "")
                    default_cmd = action.get("default", "")
                    if vrf_cmd != default_cmd and "{vrf}" not in vrf_cmd:
                        status = "FAIL"
                        issues.append("VRF template missing {vrf}")
                    if not action.get("default", "").strip():
                        status = "FAIL"
                        issues.append("empty default command")
                    if not action.get("vrf", "").strip():
                        status = "FAIL"
                        issues.append("empty vrf command")
                else:
                    status = "FAIL"
                    issues.append(f"unexpected action type: {type(action).__name__}")

                entries.append({
                    "vendor": vendor,
                    "category": cat,
                    "query": query,
                    "status": status,
                    "issues": ", ".join(issues) if issues else "",
                })
    return entries


def _collect_normalizer_coverage() -> list[dict]:
    """Check which cli_styles have parsers for each normalizer."""
    parsers = {
        "interfaces":     _INTERFACE_PARSERS,
        "ospf_neighbors": _OSPF_NEIGHBOR_PARSERS,
        "ospf_details":   _OSPF_DETAIL_PARSERS,
        "bgp_summary":    _BGP_SUMMARY_PARSERS,
        "eigrp_neighbors": _EIGRP_NEIGHBOR_PARSERS,
    }
    entries = []
    for name, parser_dict in parsers.items():
        for vendor in _VENDORS:
            has_parser = vendor in parser_dict
            # eigrp is IOS-only
            if name == "eigrp_neighbors":
                expected = vendor == "ios"
            else:
                expected = True
            status = "PASS" if (has_parser == expected) else "FAIL"
            entries.append({
                "normalizer": name,
                "vendor": vendor,
                "has_parser": has_parser,
                "expected": expected,
                "status": status,
            })
    return entries


def _write_results(cmd_entries: list[dict], norm_entries: list[dict]) -> None:
    """Write platform_coverage_results.md."""
    lines = [
        "# Platform Coverage Results",
        "",
        "_Auto-generated by IT-001 (testing/integration/test_platform_coverage.py)_",
        "",
        "## Command Coverage",
        "",
        "| Vendor | Category | Query | Status | Notes |",
        "|--------|---------|-------|--------|-------|",
    ]
    for e in cmd_entries:
        lines.append(
            f"| {e['vendor']} | {e['category']} | {e['query']} "
            f"| {e['status']} | {e['issues']} |"
        )

    lines += [
        "",
        "## Normalizer Parser Coverage",
        "",
        "| Normalizer | Vendor | Has Parser | Expected | Status |",
        "|-----------|--------|-----------|---------|--------|",
    ]
    for e in norm_entries:
        lines.append(
            f"| {e['normalizer']} | {e['vendor']} | {e['has_parser']} "
            f"| {e['expected']} | {e['status']} |"
        )

    lines += ["", "---", ""]
    _RESULTS_FILE.write_text("\n".join(lines))


# ── Test: command coverage ─────────────────────────────────────────────────────

class TestCommandCoverage:

    def setup_method(self):
        self.entries = _collect_coverage()

    def test_no_failed_entries(self):
        failed = [e for e in self.entries if e["status"] == "FAIL"]
        assert not failed, f"Failed entries:\n" + "\n".join(
            f"  {e['vendor']}/{e['category']}/{e['query']}: {e['issues']}"
            for e in failed
        )

    def test_all_vendors_covered(self):
        vendors_in_results = {e["vendor"] for e in self.entries}
        for v in _VENDORS:
            assert v in vendors_in_results

    def test_all_required_categories_covered(self):
        for vendor in _VENDORS:
            vendor_cats = {e["category"] for e in self.entries if e["vendor"] == vendor}
            for cat in _REQUIRED_CATEGORIES:
                assert cat in vendor_cats, f"{vendor} missing category {cat}"

    def test_ios_has_eigrp_category(self):
        ios_cats = {e["category"] for e in self.entries if e["vendor"] == "ios"}
        assert "eigrp" in ios_cats

    def test_non_ios_no_eigrp(self):
        for vendor in ["eos", "junos", "aos", "routeros", "vyos"]:
            vendor_cats = {e["category"] for e in self.entries if e["vendor"] == vendor}
            assert "eigrp" not in vendor_cats, f"{vendor} should not have eigrp"

    def test_vrf_templates_have_placeholder(self):
        for vendor in _VENDORS:
            vendor_entry = PLATFORM_MAP[vendor]
            for cat, queries in vendor_entry.items():
                for query, action in queries.items():
                    if isinstance(action, dict) and "vrf" in action:
                        vrf_cmd = action["vrf"]
                        default_cmd = action.get("default", "")
                        if vrf_cmd != default_cmd:
                            assert "{vrf}" in vrf_cmd, (
                                f"{vendor}/{cat}/{query} VRF cmd missing {{vrf}}"
                            )

    def test_ospf_queries_present_for_all_vendors(self):
        ospf_queries = {"neighbors", "database", "borders", "config", "interfaces", "details"}
        for vendor in _VENDORS:
            vendor_ospf = {
                e["query"] for e in self.entries
                if e["vendor"] == vendor and e["category"] == "ospf"
            }
            assert ospf_queries.issubset(vendor_ospf), (
                f"{vendor} OSPF missing: {ospf_queries - vendor_ospf}"
            )

    def test_bgp_queries_present_for_all_vendors(self):
        bgp_queries = {"summary", "table", "config", "neighbors"}
        for vendor in _VENDORS:
            vendor_bgp = {
                e["query"] for e in self.entries
                if e["vendor"] == vendor and e["category"] == "bgp"
            }
            assert bgp_queries.issubset(vendor_bgp), (
                f"{vendor} BGP missing: {bgp_queries - vendor_bgp}"
            )

    def test_interfaces_has_interface_status_query(self):
        for vendor in _VENDORS:
            intfs = {
                e["query"] for e in self.entries
                if e["vendor"] == vendor and e["category"] == "interfaces"
            }
            assert "interface_status" in intfs, f"{vendor} interfaces missing interface_status"


# ── Test: normalizer coverage ──────────────────────────────────────────────────

class TestNormalizerCoverage:

    def setup_method(self):
        self.entries = _collect_normalizer_coverage()

    def test_no_failed_entries(self):
        failed = [e for e in self.entries if e["status"] == "FAIL"]
        assert not failed, f"Normalizer coverage failures:\n" + "\n".join(
            f"  {e['normalizer']}/{e['vendor']}: has={e['has_parser']}, expected={e['expected']}"
            for e in failed
        )

    def test_all_vendors_have_interface_parser(self):
        for vendor in _VENDORS:
            assert vendor in _INTERFACE_PARSERS, f"{vendor} missing interface parser"

    def test_all_vendors_have_ospf_neighbor_parser(self):
        for vendor in _VENDORS:
            assert vendor in _OSPF_NEIGHBOR_PARSERS, f"{vendor} missing OSPF neighbor parser"

    def test_all_vendors_have_ospf_detail_parser(self):
        for vendor in _VENDORS:
            assert vendor in _OSPF_DETAIL_PARSERS, f"{vendor} missing OSPF detail parser"

    def test_all_vendors_have_bgp_parser(self):
        for vendor in _VENDORS:
            assert vendor in _BGP_SUMMARY_PARSERS, f"{vendor} missing BGP parser"

    def test_eigrp_only_ios(self):
        assert "ios" in _EIGRP_NEIGHBOR_PARSERS
        for vendor in ["eos", "junos", "aos", "routeros", "vyos"]:
            assert vendor not in _EIGRP_NEIGHBOR_PARSERS


# ── Generate results file ──────────────────────────────────────────────────────

def test_generate_coverage_results_file():
    """Generate the coverage report markdown file."""
    cmd_entries = _collect_coverage()
    norm_entries = _collect_normalizer_coverage()
    _write_results(cmd_entries, norm_entries)
    assert _RESULTS_FILE.exists()
    content = _RESULTS_FILE.read_text()
    assert "Platform Coverage Results" in content
    assert "PASS" in content
    for vendor in _VENDORS:
        assert vendor in content
