#!/usr/bin/env bash
# deploy/install.sh — install dblCheck as a systemd service
#
# Usage:
#   sudo deploy/install.sh
#
# Detects the install path and the invoking user automatically.
# No manual editing of the service file required.

set -euo pipefail

INSTALL_DIR="$(dirname "$(dirname "$(readlink -f "$0")")")"
SERVICE_DEST=/etc/systemd/system/dblcheck.service

# When run via sudo, SUDO_USER is the real user; otherwise use current user.
REAL_USER="${SUDO_USER:-$(id -un)}"
REAL_GROUP="$(id -gn "$REAL_USER")"
REAL_HOME=$(eval echo "~$REAL_USER")
SERVICE_PATH="$REAL_HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"

if [[ $EUID -ne 0 ]]; then
    echo "Error: run this script with sudo." >&2
    exit 1
fi

echo "Installing dblCheck daemon:"
echo "  Install path : $INSTALL_DIR"
echo "  Service user : $REAL_USER ($REAL_GROUP)"

cat > "$SERVICE_DEST" <<EOF
# Generated by deploy/install.sh — do not edit manually.
# Re-run  sudo deploy/install.sh  to regenerate after moving the install directory.

[Unit]
Description=dblCheck network validation daemon
After=network.target

[Service]
Type=simple
User=$REAL_USER
Group=$REAL_GROUP
Environment=PATH=$SERVICE_PATH
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=$INSTALL_DIR/dbl/bin/python deploy/dblcheck_daemon.py
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable dblcheck
systemctl restart dblcheck

echo "Done. Service status:"
systemctl status dblcheck --no-pager
